"use strict";
exports.__esModule = true;
var resgistroNotas_1 = require("./resgistroNotas");
var diario_1 = require("./diario");
var diario_2 = require("./diario");
var kaua = new resgistroNotas_1.registroNotas("Kauã H", 20251148060019, 60, 50);
var lucas = new resgistroNotas_1.registroNotas("Lucas", 20251148060000, 76, 80);
var marcos = new resgistroNotas_1.registroNotas("Marcos", 20251180609, 10, 70);
var giovanna = new resgistroNotas_1.registroNotas("Giovanna", 2040619, 80, 90);
var carlito = new resgistroNotas_1.registroNotas("Carlito", 2486465420019, 10, 30);
var aluno = new diario_1.diario("POO", "KAUA", "TSI", "B123", 100, diario_2.turno.turnoVes);
console.log(kaua.calcularMedia());
console.log(kaua.calcularMediaFinal(5));
console.log(lucas.calcularMedia());
console.log(lucas.calcularMediaFinal(50));
console.log(marcos.calcularMedia());
console.log(marcos.calcularMediaFinal(80));
console.log(giovanna.calcularMedia());
console.log(giovanna.calcularMediaFinal());
console.log(carlito.calcularMedia());
console.log(carlito.calcularMediaFinal(50));
aluno.adicionarEstudante(kaua);
aluno.adicionarEstudante(lucas);
aluno.adicionarEstudante(marcos);
aluno.adicionarEstudante(giovanna);
aluno.adicionarEstudante(carlito);
aluno.registroNotas.forEach(function (estudante) {
    console.log('- ' + estudante.nomeEstudante + ': MediaParcial ' + estudante.mediaParcial + ', MediaFinal ' + estudante.mediaFinal + ', Situação: ' + estudante.situacaoEstudante);
});
